// Mock data for frontend-only development

export const mockUser = {
  id: "demo-user-1",
  email: "demo@example.com",
  firstName: "Demo",
  lastName: "User",
  profileImageUrl: null,
  roleId: "customer",
  planId: "growth",
  status: "active",
  automationsCount: 3,
  messagesThisMonth: 450,
  lastMessageReset: new Date().toISOString(),
  companyName: "Demo Company",
  instagramHandle: "@demo",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  plan: {
    id: "growth",
    name: "Growth",
    description: "For growing businesses",
    priceMonthly: 99900,
    priceYearly: 999900,
    maxAutomations: 5,
    maxMessagesPerMonth: 1000,
    maxKeywordsPerAutomation: 10,
    displayOrder: 2,
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  role: {
    id: "customer",
    name: "Customer",
    description: "Regular user",
    permissions: ["automation:view", "automation:create", "automation:edit", "automation:delete", "automation:toggle", "analytics:view", "settings:view", "settings:edit", "billing:view"],
    isSystemRole: true,
    displayOrder: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  planFeatures: ["instagram_dm", "comment_automation", "story_automation", "dm_automation", "card_messages", "multi_keyword", "analytics_advanced"],
};

export const mockAutomations = [
  {
    id: 1,
    userId: "demo-user-1",
    name: "Diwali Sale Reply",
    category: "COMMENT",
    status: true,
    triggerType: "specific",
    keywords: ["diwali", "sale", "offer", "discount"],
    replyOnShare: false,
    sendPublicReply: true,
    followersOnly: false,
    messageType: "text",
    messageContent: "Namaste! 🪔 Thank you for your interest in our Diwali collection! Check your DM for exclusive 30% off code!",
    runs: 1250,
    dmsSent: 890,
    dmsSeen: 756,
    engaged: 234,
    clicks: 189,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    userId: "demo-user-1",
    name: "New Arrival Inquiry",
    category: "DM",
    status: true,
    triggerType: "specific",
    keywords: ["new", "arrival", "latest", "collection"],
    replyOnShare: false,
    sendPublicReply: false,
    followersOnly: false,
    messageType: "card",
    messageContent: "Hi! Our latest collection just dropped! 🎉 Here are some trending pieces...",
    runs: 780,
    dmsSent: 620,
    dmsSeen: 540,
    engaged: 189,
    clicks: 156,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockPlans = [
  {
    id: "starter",
    name: "Starter",
    description: "Perfect for getting started with Instagram automation",
    priceMonthly: 0,
    priceYearly: 0,
    maxAutomations: 1,
    maxMessagesPerMonth: 100,
    maxKeywordsPerAutomation: 3,
    displayOrder: 1,
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "growth",
    name: "Growth",
    description: "For growing businesses that need more power",
    priceMonthly: 99900,
    priceYearly: 999900,
    maxAutomations: 5,
    maxMessagesPerMonth: 1000,
    maxKeywordsPerAutomation: 10,
    displayOrder: 2,
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "scale",
    name: "Scale",
    description: "For businesses ready to scale their automation",
    priceMonthly: 249900,
    priceYearly: 2499900,
    maxAutomations: 25,
    maxMessagesPerMonth: 10000,
    maxKeywordsPerAutomation: 50,
    displayOrder: 3,
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockFeatures = [
  { id: "instagram_dm", name: "Instagram DM Automation", category: "channel", isActive: true, isComingSoon: false, icon: "Instagram", displayOrder: 1 },
  { id: "comment_automation", name: "Comment Triggers", category: "automation", isActive: true, isComingSoon: false, icon: "MessageSquare", displayOrder: 4 },
  { id: "story_automation", name: "Story Replies", category: "automation", isActive: true, isComingSoon: false, icon: "Image", displayOrder: 5 },
  { id: "analytics_basic", name: "Basic Analytics", category: "analytics", isActive: true, isComingSoon: false, icon: "BarChart", displayOrder: 7 },
];

export const mockUsers = [
  {
    id: "demo-user-1",
    email: "demo@example.com",
    firstName: "Demo",
    lastName: "User",
    profileImageUrl: null,
    roleId: "customer",
    planId: "growth",
    status: "active",
    automationsCount: 3,
    messagesThisMonth: 450,
    lastMessageReset: new Date().toISOString(),
    companyName: "Demo Company",
    instagramHandle: "@demo",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-user-2",
    email: "admin@example.com",
    firstName: "Admin",
    lastName: "User",
    profileImageUrl: null,
    roleId: "admin",
    planId: "scale",
    status: "active",
    automationsCount: 12,
    messagesThisMonth: 3500,
    lastMessageReset: new Date().toISOString(),
    companyName: "Admin Company",
    instagramHandle: "@admin",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-user-3",
    email: "test@example.com",
    firstName: "Test",
    lastName: "User",
    profileImageUrl: null,
    roleId: "customer",
    planId: "starter",
    status: "inactive",
    automationsCount: 1,
    messagesThisMonth: 50,
    lastMessageReset: new Date().toISOString(),
    companyName: "Test Company",
    instagramHandle: "@test",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockRoles = [
  {
    id: "customer",
    name: "Customer",
    description: "Regular user with standard permissions",
    permissions: [
      "automation:view",
      "automation:create",
      "automation:edit",
      "automation:delete",
      "automation:toggle",
      "analytics:view",
      "settings:view",
      "settings:edit",
      "billing:view",
    ],
    isSystemRole: true,
    displayOrder: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "admin",
    name: "Admin",
    description: "Administrator with full system access",
    permissions: [
      "automation:view",
      "automation:create",
      "automation:edit",
      "automation:delete",
      "automation:toggle",
      "analytics:view",
      "analytics:export",
      "settings:view",
      "settings:edit",
      "team:view",
      "team:invite",
      "team:remove",
      "team:edit_roles",
      "billing:view",
      "billing:manage",
      "admin:access",
      "admin:users",
      "admin:plans",
      "admin:features",
      "admin:analytics",
      "users.view",
      "users.create",
      "users.edit",
      "users.delete",
      "admin.access",
      "settings.view",
      "settings.edit",
      "billing.view",
      "billing.manage",
      "refunds.process",
    ],
    isSystemRole: true,
    displayOrder: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "editor",
    name: "Editor",
    description: "Editor with limited administrative permissions",
    permissions: [
      "automation:view",
      "automation:create",
      "automation:edit",
      "automation:toggle",
      "analytics:view",
      "settings:view",
      "settings:edit",
      "team:view",
    ],
    isSystemRole: false,
    displayOrder: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "viewer",
    name: "Viewer",
    description: "View-only access with limited permissions",
    permissions: [
      "automation:view",
      "analytics:view",
      "settings:view",
    ],
    isSystemRole: false,
    displayOrder: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockPayments = [
  {
    id: 1,
    userId: "demo-user-1",
    razorpayOrderId: "order_1234567890",
    razorpayPaymentId: "pay_1234567890",
    razorpaySignature: null,
    amount: 99900, // ₹999 in paise
    currency: "INR",
    status: "paid",
    planId: "growth",
    billingCycle: "monthly",
    receipt: "receipt_001",
    notes: null,
    failureReason: null,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), // 7 days ago
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    userId: "demo-user-2",
    razorpayOrderId: "order_0987654321",
    razorpayPaymentId: "pay_0987654321",
    razorpaySignature: null,
    amount: 249900, // ₹2,499 in paise
    currency: "INR",
    status: "paid",
    planId: "scale",
    billingCycle: "monthly",
    receipt: "receipt_002",
    notes: null,
    failureReason: null,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days ago
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    userId: "demo-user-1",
    razorpayOrderId: "order_1122334455",
    razorpayPaymentId: null,
    razorpaySignature: null,
    amount: 99900,
    currency: "INR",
    status: "created",
    planId: "growth",
    billingCycle: "monthly",
    receipt: "receipt_003",
    notes: null,
    failureReason: null,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 4,
    userId: "demo-user-3",
    razorpayOrderId: "order_5544332211",
    razorpayPaymentId: "pay_failed_001",
    razorpaySignature: null,
    amount: 0,
    currency: "INR",
    status: "failed",
    planId: "starter",
    billingCycle: "monthly",
    receipt: "receipt_004",
    notes: null,
    failureReason: "Payment declined by bank",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days ago
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 5,
    userId: "demo-user-2",
    razorpayOrderId: "order_6677889900",
    razorpayPaymentId: "pay_6677889900",
    razorpaySignature: null,
    amount: 2499900, // ₹24,999 in paise (yearly)
    currency: "INR",
    status: "paid",
    planId: "scale",
    billingCycle: "yearly",
    receipt: "receipt_005",
    notes: null,
    failureReason: null,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(), // 30 days ago
    updatedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 6,
    userId: "demo-user-1",
    razorpayOrderId: "order_7788990011",
    razorpayPaymentId: null,
    razorpaySignature: null,
    amount: 999900, // ₹9,999 in paise (yearly growth plan)
    currency: "INR",
    status: "created",
    planId: "growth",
    billingCycle: "yearly",
    receipt: "receipt_006",
    notes: null,
    failureReason: null,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
];

// Re-export PERMISSIONS for convenience (matches usePermissions.ts)
export const PERMISSIONS = {
  AUTOMATION_VIEW: 'automation:view',
  AUTOMATION_CREATE: 'automation:create',
  AUTOMATION_EDIT: 'automation:edit',
  AUTOMATION_DELETE: 'automation:delete',
  AUTOMATION_TOGGLE: 'automation:toggle',
  ANALYTICS_VIEW: 'analytics:view',
  ANALYTICS_EXPORT: 'analytics:export',
  SETTINGS_VIEW: 'settings:view',
  SETTINGS_EDIT: 'settings:edit',
  TEAM_VIEW: 'team:view',
  TEAM_INVITE: 'team:invite',
  TEAM_REMOVE: 'team:remove',
  TEAM_EDIT_ROLES: 'team:edit_roles',
  BILLING_VIEW: 'billing:view',
  BILLING_MANAGE: 'billing:manage',
  ADMIN_ACCESS: 'admin:access',
  ADMIN_USERS: 'admin:users',
  ADMIN_PLANS: 'admin:plans',
  ADMIN_FEATURES: 'admin:features',
  ADMIN_ANALYTICS: 'admin:analytics',
} as const;

